-- AlterTable
ALTER TABLE `jobapplication` MODIFY `application_date` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `firstname` VARCHAR(100) NULL,
    MODIFY `lastname` VARCHAR(100) NULL,
    MODIFY `job_position` VARCHAR(150) NULL,
    MODIFY `expected_salary` DOUBLE NULL,
    MODIFY `documents` JSON NULL,
    MODIFY `personal_info` JSON NULL,
    MODIFY `phone_number` VARCHAR(20) NULL,
    MODIFY `email` VARCHAR(150) NULL,
    MODIFY `liveby` VARCHAR(191) NULL,
    MODIFY `birth_date` DATE NULL,
    MODIFY `age` INTEGER NULL,
    MODIFY `ethnicity` VARCHAR(50) NULL,
    MODIFY `nationality` VARCHAR(50) NULL,
    MODIFY `religion` VARCHAR(50) NULL,
    MODIFY `marital_status` VARCHAR(50) NULL,
    MODIFY `military_status` VARCHAR(100) NULL,
    MODIFY `photo` VARCHAR(191) NULL;
